### PR TITLE
CSS and javascript files now saved to project file, included in .zip …

### PR DESCRIPTION
**Pull request by davidjamesbeck**
…file, and downloaded as part of project

### CODE REVIEW

**Comment by paul-shannon** [comment]
@davidjamesbeck  your apprenticeship is complete!  very nice

**Comment by davidjamesbeck** [comment]
Yay! I won’t tell you how long it actually took me to perfect those 4 lines of code …

You’ll note, by the way, that the method for creating the .zip file copies the .css and .js files into the project directory. This is because I couldn’t figure out how to make the ZipFile object just copy the files from where they live in the slexil directory into the .zip file without recreating the absolute path to the originals. That said, I am not too bothered by this since slexil creates copies of the .eaf, .html, etc., in the project folder anyway. However, it does bring up a question: presumably, when this is running online, it will be building project folders on the server side for everything that gets processed. Which means copies of people texts will be left, and will proliferate, on the university server?

That might raise some proprietary issues, and eventually storage space issues.

Cheers,

David

**Comment by paul-shannon** [comment]
Software, like sausage:  we don’t want anyone to know how awful is our intermediate work.  

It would be reasonable, I think, to run a daily cron job to delete all PROJECT directories older than some amount.   Is your University computational/IT group pretty helpful?  Do you have the political heft, or are they unburdened enough, to get some real support from them?  IT people are so often beleaguered, over-worked, unappreciated - and thus defensive.

**Comment by davidjamesbeck** [comment]
The IT group here has been pretty good to me, so that sounds like an option, especially if it can be automated. The people I work with work mostly with Arts and Humanities types, so I suspect that they find dealing with linguists refreshing.

I have now figured out how to link a .css file into a dash .app (using that tutorial you pointed me to, and then StackOverflow to find out why what he said didn’t work quite the way he said it would), so I may open a branch to work on styling the page a bit. The approach I think would work best would be to start replacing the “style” attributes in the various divs with “className” attributes, and transfer the style attributes of the classes to a .css file, then edit that as needed. I suppose there can be a branch for this (which will take a while) while there is another for couple of other, more constrained issues? If not, I’ll just play with a stylesheet outside git.

I think in terms of functionality, I could try my hand at adding capacity for the two extra line types to the webapp. I think I have a pretty good idea of how that can be done. 

David

**Comment by paul-shannon** [comment]
All of that sounds good, David.

A “cron job <https://linuxize.com/post/scheduling-cron-jobs-with-crontab/>” is automated - by its very nature: just a script that runs in the background periodically.


Excellent idea to replace hard-coded style with className.  That had not occurred to me.

In adding those two lines to webapp.py, I wish I could point you to a standalone & exploratory version of the tier mapping menus.   Any UI feature that complicated should by rights live in its own file, with a simple python “test harness” script to invoke it.   This is another instance of the meta-strategy divide and conquer.  

I may have had that at one point, but in haste I moved the code into webapp.py and did my last debugging there. Short-sighted of me, and now making things a bit harder for you.

def createTierMappingMenus(eafFilename) in webapp.py is (as you probably figure out) a good place to begin.

 - Paul

**Pull request merged**
