### PR TITLE
workflow control implementation

### PR DESCRIPTION
**Pull request by davidjamesbeck**

### CODE REVIEW

**Comment by davidjamesbeck** [comment]
That was fast! You’re a trusting soul … :-)

**Comment by paul-shannon** [comment]
Hi David,

I just tried the new version after merging and a git pull.  I had a little trouble

  - I am confused over abbreviations vs grammaticalTerms
  - it took me a moment to understand that the tier guide UI has examples from another story in the middle column
  - morphemePacking "word boundaries"  - shouldn't this be a mandatory field
 - webapp.py crashed with the choices I made:

````
-------- entering createWebPage
eafFileName: PROJECTS/slomo/inferno-threeLines.eaf
projectDirectory: PROJECTS/slomo
audioDirectoryRelativePath: audio
grammaticalTermsFile: None
tierGuideFile: PROJECTS/slomo/tierGuide.yaml
[2019-05-07 15:17:31,719] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/paul/anaconda/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/paul/anaconda/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/paul/anaconda/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/paul/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/paul/anaconda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/paul/anaconda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/paul/anaconda/lib/python3.6/site-packages/dash/dash.py", line 1151, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "/Users/paul/anaconda/lib/python3.6/site-packages/dash/dash.py", line 1037, in add_context
    output_value = func(*args, **kwargs)
  File "webapp.py", line 753, in createWebPageCallback
    os.path.join(projectDirectory, "tierGuide.yaml"))
  File "webapp.py", line 1038, in createWebPage
    return(text.toHTML())
  File "/Users/paul/github/slexil/text.py", line 146, in toHTML
    line.toHTML(htmlDoc)
  File "/Users/paul/github/slexil/ijalLine.py", line 233, in toHTML
    mg = MorphemeGloss(morphemeGloss, self.grammaticalTerms)
  File "/Users/paul/github/slexil/morphemeGloss.py", line 52, in __init__
    self.grammaticalTerms = _makeAbbreviationListLowerCase(grammaticalTerms)
  File "/Users/paul/github/slexil/morphemeGloss.py", line 126, in _makeAbbreviationListLowerCase
    for term in terms:
TypeError: 'NoneType' object is not iterable
````

**Comment by davidjamesbeck** [comment]
Hi, Paul

“Abbreviations” is just a more user-friendly label for what we are calling “grammatical terms”. It only appears in the label in the TierMap, not anywhere in the code.

“morpheme packing” isn’t actually correct since the tabs we’re working with delimit words, whereas morphemes are divided by n-dashes, etc. A user won't understand what we were thinking. But this still only affects the labels and messages, not the programming. If you don’t select a value for that, you’re supposed to get an error message when you click on the button—did that not work for you? Or did you just mean I should add an asterisk after the label (good idea, actually)?

Since there aren’t 100% standardized terms for the parts of an interlinear gloss, I am not sure that everyone will understand what piece goes with what, so an example analysis seemed like a good way to go. Do you think that a column header for the middle column (“For example …”) would make it less confusing? Or moving the example to the right edge of the TierMapping box? I was also originally thinking of putting lines from the Inferno demo in the tier map, but anything with more than one word will be a problem in terms of vertical alignment. 

The error below looks like it might be the use case where there is no grammatical terms file selected, no? I didn’t try that one (d’oh!).

On another matter, I note that the error is being generated by some lines of code that we don’t need anymore. The conversion of the grammatical terms to lowercase (and the replacement of hyphens with n-dashes) in MorphemeGloss is actually redundant and computationally costly because it is run for every morpheme gloss when we can actually run them once in IjalLine and be done with it. I just left them in because some of the tests we were using go directly to MorphemeGloss and bypass IjalLine. If we’re done with those tests, we could remove these lines (line 50 and 53 in morphemeGloss.py) and the non-class functions they call. (I know that won’t necessarily clear the error, but I was wondering at what point we would clean things like this up.)

Thanks for testing.

David

**Comment by davidjamesbeck** [comment]
Hi, Paul

I’m trying to recreate the error below, but I don’t see how you got to createWebPage without specifying a grammatical terms file. The “Show page” button” is disabled until that is done. 

David

**Pull request merged**
